name: yet_another_lint
description: Highly opinionated set of Dart / Flutter linter rules
homepage: https://github.com/notDmDrl/yet_another_lint
repository: https://github.com/notDmDrl/yet_another_lint
version: 1.0.10

publish_to: none

topics:
  - analysis
  - lints

environment:
  sdk: ^3.11.0-296.3.beta